/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Clases.ImagenFondo;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 * @author Sebastian Toro Cano
 * @author Sebastian Galeano Bolivar
 * @version 1
 */
public class frmPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipalOrtho
     */
    public frmPrincipalAdmin() {
        initComponents();
        dpnEscritorio.setBorder(new ImagenFondo());
        this.setExtendedState(frmPrincipalAdmin.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        dpnEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuContacProveedores = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mnuAyuda = new javax.swing.JMenu();
        JmenuItemUsuario = new javax.swing.JMenuItem();
        JmenuItemTecnico = new javax.swing.JMenuItem();
        MnuSalir = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar5.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar5.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Principal");

        dpnEscritorio.setBackground(new java.awt.Color(102, 102, 102));

        mnuContacProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proveedor.png"))); // NOI18N
        mnuContacProveedores.setText("Proveedores");
        mnuContacProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuContacProveedoresMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuContacProveedores);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contactos.png"))); // NOI18N
        jMenu2.setText("Acerca de");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ayuda1.png"))); // NOI18N
        mnuAyuda.setText("Ayuda");
        mnuAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAyudaMouseClicked(evt);
            }
        });
        mnuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudaActionPerformed(evt);
            }
        });

        JmenuItemUsuario.setText("Manual De Usuario");
        JmenuItemUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JmenuItemUsuarioMouseClicked(evt);
            }
        });
        JmenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuItemUsuarioActionPerformed(evt);
            }
        });
        mnuAyuda.add(JmenuItemUsuario);

        JmenuItemTecnico.setText("Manual Tecnico");
        JmenuItemTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JmenuItemTecnicoMouseClicked(evt);
            }
        });
        JmenuItemTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuItemTecnicoActionPerformed(evt);
            }
        });
        mnuAyuda.add(JmenuItemTecnico);

        jMenuBar1.add(mnuAyuda);

        MnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir.png"))); // NOI18N
        MnuSalir.setText("Salir");
        MnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(MnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuContacProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuContacProveedoresMouseClicked
        frmProveedores_1 proveedores = new frmProveedores_1();
        dpnEscritorio.add(proveedores);
        proveedores.show();
    }//GEN-LAST:event_mnuContacProveedoresMouseClicked

    private void MnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnuSalirMouseClicked
        int rta = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro que deseas salir?");
        if (rta != 0) {
            return;
        }

        frmIngresar ingresar = new frmIngresar();
        ingresar.show();
        this.dispose();
    }//GEN-LAST:event_MnuSalirMouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        acerca_de acerca = new acerca_de();
        acerca.setLocationRelativeTo(null);
        acerca.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void JmenuItemUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JmenuItemUsuarioMouseClicked

    }//GEN-LAST:event_JmenuItemUsuarioMouseClicked

    private void JmenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuItemUsuarioActionPerformed
        try {
            File path = new File ("C:/Users/Usuario/Documents/2016-1/Implantar/OrthoGarcia/Orthogarcia 02052016/OrthoGarcia08Diciembre/Manual-de-usuario-orthogarcia.docx");
            Desktop.getDesktop().open(path);
        }catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_JmenuItemUsuarioActionPerformed

    private void JmenuItemTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JmenuItemTecnicoMouseClicked

    }//GEN-LAST:event_JmenuItemTecnicoMouseClicked

    private void JmenuItemTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuItemTecnicoActionPerformed

        try {
            File path = new File ("C:/Users/Usuario/Documents/2016-1/Implantar/OrthoGarcia/Orthogarcia 02052016/OrthoGarcia08Diciembre/MANUAL TÉCNICO  DEL SOFTWARE ORTHOGARCIA.docx");
            Desktop.getDesktop().open(path);
        }catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_JmenuItemTecnicoActionPerformed

    private void mnuAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAyudaMouseClicked

    }//GEN-LAST:event_mnuAyudaMouseClicked

    private void mnuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudaActionPerformed

    }//GEN-LAST:event_mnuAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JmenuItemTecnico;
    private javax.swing.JMenuItem JmenuItemUsuario;
    private javax.swing.JMenu MnuSalir;
    private javax.swing.JDesktopPane dpnEscritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuContacProveedores;
    // End of variables declaration//GEN-END:variables
}
